version: "3.4"
services:
  hostapd:
    build: hostapd_docker
    image: "hostapd"
    network_mode: host
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    environment:
      - WPA2_ESSID=${WPA2_ESSID:-cottagewifi}
      - WPA2_PASSWORD=${WPA2_PASSWORD:-password12345}
    volumes:
      - ./hostapd_docker/confs/hostapd_confs/wpa2.conf:/etc/hostapd/hostapd.conf
    restart: always
  dhcpd:
    build: dhcp_docker/docker-dhcpd-master/
    image: "dhcpd"
    volumes: 
       - ./dhcp_docker/data:/data 
    network_mode: host
    restart: always
    depends_on: 
      - hostapd
  ntp:
    build: ntp_docker/
    image: "ntp"
    cap_add:
      - SYS_TIME
    ports: 
      - "123:123/udp"
    volumes:
      - ./ntp_docker/conf:/etc/chrony
    restart: always

    